name: Go Build and Release
on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get Go dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -ldflags "-X main.version=${GITHUB_REF#refs/tags/}" -o ermon .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ermon
          token: ${{ secrets.GITHUB_TOKEN }}
